# Generated by Django 5.1.2 on 2024-11-20 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='users.profile', verbose_name='Друзья'),
        ),
    ]
