# Generated by Django 5.1.2 on 2024-11-08 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_group_banner'),
        ('users', '0004_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Описание профиля'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='groups', to='groups.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, related_name='related_profiles', to='groups.interest', verbose_name='Интересы'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(blank=True, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=32, unique=True, verbose_name='Никнейм'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname_ds',
            field=models.CharField(blank=True, null=True, verbose_name='Никнейм в Discord'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname_tg',
            field=models.CharField(blank=True, null=True, verbose_name='Никнейм в Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='study_at',
            field=models.CharField(blank=True, null=True, verbose_name='Учебное заведение'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='surname',
            field=models.CharField(blank=True, null=True, verbose_name='Фамилия'),
        ),
    ]
