version: '3.8'

networks:
    traefik-net:
      name: traefik-net
      external: true
    case-net:
      name: case-net
      driver: bridge

services:
  case_web:
    build:
      target: production_build
      args:
        DJANGO_ENV: production
    restart: unless-stopped
    container_name: case_web
    command: gunicorn school21_case.wsgi:application --bind 0.0.0.0:8000 --workers=4 --log-file=- --worker-tmp-dir='/dev/shm'
    volumes:
      - django-media:/code/media
      - django-static:/code/static
    networks:
      - case-net
    environment:
      - DJANGO_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  case_db:
    container_name: case_db
    image: postgres:17
    volumes:
      - case_data:/var/lib/postgresql/data/
    networks:
      - case-net
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}

  case_nginx:
    build: ./nginx
    volumes:
      - django-media:/code/media
      - django-static:/code/static
      - ./nginx/ssl:/etc/nginx/ssl
      - ./nginx/config:/etc/nginx/config
      - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
      - ./nginx/letsencrypt:/usr/share/nginx/html/letsencrypt:rw
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx.rule=Host(`case.ru`) || Host(`www.case.ru`)
      - traefik.http.services.nginx.loadbalancer.server.port=80
    networks:
      - case-net
      - traefik-net
    container_name: case_nginx
    depends_on:
      - case_db

volumes:
  django-media:
  django-static:
  case_data:
