# Generated by Django 5.1.2 on 2024-11-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_remove_group_logo_group_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='banner',
            field=models.ImageField(null=True, upload_to='group_banners/'),
        ),
    ]
